version: "0.5"
is_strict: true
sort:
  isReversed: true

.song: &song
  command: |
    watchman-make \
      --make 'make --makefile=../../song.mk' \
      --pattern '*.*ly' \
      --pattern '**/*.*ly' \
      --target all
  depends_on:
    watchman:
      condition: process_started

processes:
  watchman:
    command: "watchman --foreground"
  music_number:
    <<: *song
    working_dir: "songs/music_number"
  whats_real:
    <<: *song
    working_dir: "songs/whats_real"
