version: "0.5"

processes:
  watchman:
    command: |
      watchman --foreground
  watchman-make:
    command: |
      watchman-make \
        --make 'make --makefile=../../song.mk' \
        --pattern '*.*ly' \
        --pattern '**/*.*ly' \
        --target all
    depends_on:
      watchman:
        condition: process_started
    working_dir: "songs/whats_real"
