name: Build site

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: yurrriq
          skipPush: true
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nixpkgs
          echo '{ allowUnfree = true; }' >~/.config/nixpkgs/config.nix
      - id: pages
        name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Build with Nix
        run: |
          nix build --out-link ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GiHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
